export const GET_REQUESTS = 'GET_REQUESTS';
export const REQUESTS_ERROR = 'REQUESTS_ERROR'

export const GET_REQUESTS_PENDING = 'GET_REQUESTS_PENDING';
export const GET_REQUESTS_FULFILLED = 'GET_REQUESTS_FULFILLED';
export const GET_REQUESTS_REJECTED = 'GET_REQUESTS_REJECTED';